"""
MadAnalysis5 Tools for Collider Agent

Primary tool:
- madanalysis_process() - Run MadAnalysis5 analysis and produce plots/cutflows
- read_event_index()    - Parse event_index.yaml to locate event files for a given process

Local fallback (not exported at package level):
- connect_to_madanalysis() - Execute MadAnalysis5 normal-mode commands via local subprocess

For detailed MadAnalysis5 syntax and workflow, see prompts/madanalysis_reference.md

Author: Collider Agent
Date: 2026-02-13
"""

import os
import glob
import json
import logging
import subprocess
import tempfile
import traceback
from pathlib import Path
from typing import Dict, Any, Optional

from dotenv import load_dotenv; load_dotenv()
import magnus
import yaml

logger = logging.getLogger(__name__)

__all__ = ["read_event_index", "madanalysis_process"]


# ---------------------------------------------------------------------------
# Tool 1: read_event_index
# ---------------------------------------------------------------------------

def read_event_index(
    yaml_path: str,
    process_name: str,
    event_set_name: str = "14TeV",
) -> Dict[str, Any]:
    """
    Read event_index.yaml and return event file paths for a given process.

    The event_index.yaml is auto-generated by the simulation step and maps
    process names to their event file locations.

    Args:
        yaml_path: Path to event_index.yaml
        process_name: Process key (e.g. "pp_to_tt_3l", "pp_to_tS_3l_decay")
        event_set_name: Energy label (default "14TeV")

    Returns:
        dict: {
            "success": bool,
            "process_name": str,
            "base_path": str,          # Relative path of the process
            "runs": list[dict],         # List of run entries with path, nevents, etc.
            "event_files": list[str],   # Resolved event file paths (auto-detected)
            "message": str
        }

    Event file auto-detection order per run directory:
        1. tag_*_delphes_events.lhco.gz  (reco-level, LHCO)
        2. tag_*_delphes_events.root     (reco-level, ROOT)
        3. tag_*_pythia8_events.hepmc.gz (hadron-level)
        4. unweighted_events.lhe.gz      (parton-level)
    """
    result = {
        "success": False,
        "process_name": process_name,
        "base_path": "",
        "runs": [],
        "event_files": [],
        "message": "",
    }

    try:
        with open(yaml_path, "r") as f:
            data = yaml.safe_load(f)

        if not data or process_name not in data:
            available = list(data.keys()) if data else []
            result["message"] = (
                f"Process '{process_name}' not found in {yaml_path}. "
                f"Available: {available}"
            )
            return result

        # Find the matching event set
        process_block = data[process_name]
        if not isinstance(process_block, list):
            result["message"] = f"Unexpected format for process '{process_name}'"
            return result

        config = None
        for entry in process_block:
            if isinstance(entry, dict) and event_set_name in entry:
                config = entry[event_set_name]
                break

        if config is None:
            result["message"] = (
                f"Event set '{event_set_name}' not found for process '{process_name}'"
            )
            return result

        result["base_path"] = config.get("path", "")
        runs = config.get("runs", [])
        result["runs"] = runs

        # Auto-detect event files for each run
        event_files = []
        for run in runs:
            run_path = run.get("path", "")
            if not run_path:
                continue
            found = _find_event_file(run_path)
            if found:
                event_files.append(found)

        result["event_files"] = event_files
        result["success"] = True
        result["message"] = (
            f"Found {len(runs)} run(s) for {process_name}/{event_set_name}, "
            f"{len(event_files)} event file(s) detected"
        )
        logger.info(result["message"])

    except Exception as e:
        result["message"] = f"Error reading event index: {e}"
        logger.error(result["message"], exc_info=True)

    return result


def _find_event_file(run_dir: str) -> Optional[str]:
    """Find the best event file in a run directory, preferring higher-level formats."""
    search_patterns = [
        "tag_*_delphes_events.lhco.gz",
        "tag_*_delphes_events.lhco",
        "tag_*_delphes_events.root",
        "tag_*_pythia8_events.hepmc.gz",
        "tag_*_pythia8_events.hepmc",
        "unweighted_events.lhe.gz",
        "unweighted_events.lhe",
    ]
    for pattern in search_patterns:
        matches = glob.glob(os.path.join(run_dir, pattern))
        if matches:
            return matches[0]
    return None


# ---------------------------------------------------------------------------
# Tool 2: connect_to_madanalysis
# ---------------------------------------------------------------------------

def connect_to_madanalysis(
    script: str,
    level: str = "reco",
    timeout: int = 600,
    ma5_path: Optional[str] = None,
) -> Dict[str, Any]:
    """
    Execute MadAnalysis5 normal-mode commands.

    This is the main interface to MadAnalysis5. It accepts either:
    1. A multi-line string of MA5 commands
    2. A path to an existing .ma5 script file

    Args:
        script: MadAnalysis5 commands (string) or path to .ma5 script file
        level: Analysis level - "parton" (-P), "hadron" (-H), or "reco" (-R)
                Default: "reco"
        timeout: Maximum execution time in seconds (default: 600 = 10 minutes)
        ma5_path: Path to ma5 executable (optional, uses MA5_PATH env var)

    Returns:
        dict: {
            "success": bool,
            "stdout": str,
            "stderr": str,
            "return_code": int,
            "message": str
        }

    Analysis Levels:
    ----------------
    - "parton" (-P): For LHE files (no showering). No jet clustering.
    - "hadron" (-H): For HepMC files (showered events). FastJet available.
    - "reco"   (-R): For LHCO/ROOT files (detector-simulated). Reconstructed objects.

    Normal Mode Workflow:
    --------------------
    1. import <filepath> [as <name>]   - Load event files
    2. set <dataset>.type = signal     - Configure dataset type
    3. set main.lumi = 100             - Set luminosity
    4. plot PT(mu) 50 0 500            - Define histograms
    5. select N(j) >= 2                - Apply event selections
    6. submit <output_name>            - Run analysis and produce reports

    Example - Basic reco-level analysis:
        script = '''
        import /path/to/events.lhco.gz as signal
        set signal.type = signal
        set main.lumi = 100
        plot MET 50 0 500
        select N(j) >= 2
        submit my_analysis
        '''
        result = connect_to_madanalysis(script, level="reco")

    For complete reference, see prompts/madanalysis_reference.md
    """
    # Find MadAnalysis5 executable
    ma5_executable = _find_ma5_executable(ma5_path)

    if not ma5_executable:
        return {
            "success": False,
            "stdout": "",
            "stderr": "",
            "return_code": -1,
            "message": "MadAnalysis5 not found. Set MA5_PATH environment variable.",
        }

    # Map level to command-line flag
    level_flags = {
        "parton": "-P",
        "hadron": "-H",
        "reco": "-R",
    }
    level_flag = level_flags.get(level.lower())
    if not level_flag:
        return {
            "success": False,
            "stdout": "",
            "stderr": "",
            "return_code": -1,
            "message": (
                f"Invalid level '{level}'. Use 'parton', 'hadron', or 'reco'."
            ),
        }

    logger.info(f"Executing MadAnalysis5 in {level} mode...")

    result = {
        "success": False,
        "stdout": "",
        "stderr": "",
        "return_code": -1,
        "message": "",
    }

    try:
        # Check if script is a file path or command string
        script_path = Path(script.strip())

        if script_path.exists() and script_path.suffix == ".ma5":
            logger.info(f"Running script file: {script_path}")
            script_file = str(script_path)
            cleanup_script = False
        else:
            # Write commands to temp file
            with tempfile.NamedTemporaryFile(
                mode="w", suffix=".ma5", delete=False
            ) as f:
                f.write(script)
                script_file = f.name
            cleanup_script = True
            logger.debug(f"Script written to {script_file}")

        # Execute MadAnalysis5: ./bin/ma5 <level_flag> -s <script>
        # -s flag: auto-quit after script execution
        cmd = [str(ma5_executable), level_flag, "-s", script_file]

        proc = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=timeout,
        )

        result["stdout"] = proc.stdout
        result["stderr"] = proc.stderr
        result["return_code"] = proc.returncode
        result["success"] = proc.returncode == 0

        if result["success"]:
            result["message"] = "MadAnalysis5 execution completed successfully"
            logger.info(result["message"])
        else:
            result["message"] = (
                f"MadAnalysis5 failed with return code {proc.returncode}"
            )
            logger.error(f"MadAnalysis5 error: {proc.stderr}")

        # Cleanup temp file
        if cleanup_script:
            os.unlink(script_file)

    except subprocess.TimeoutExpired:
        result["message"] = (
            f"MadAnalysis5 execution timed out after {timeout} seconds"
        )
        logger.error(result["message"])
    except Exception as e:
        result["message"] = f"MadAnalysis5 execution error: {e}"
        logger.error(result["message"], exc_info=True)

    return result


def _find_ma5_executable(ma5_path: Optional[str] = None) -> Optional[Path]:
    """Find MadAnalysis5 executable."""
    # Priority: argument > environment variable
    path = ma5_path or os.getenv("MA5_PATH")

    if not path:
        return None

    ma5_bin = Path(path)

    # Handle both directory and direct executable path
    if ma5_bin.is_dir():
        executable = ma5_bin / "ma5"
    else:
        executable = ma5_bin

    if executable.exists():
        return executable

    return None


# ---------------------------------------------------------------------------
# Tool 3: madanalysis_process
# ---------------------------------------------------------------------------

def madanalysis_process(
    events_path: str,
    script: str,
    target_path: str,
    level: str = "parton",
) -> Dict[str, Any]:
    """
    Run MadAnalysis5 analysis.

    Takes the process directory from madgraph_launch (containing Events/)
    and runs a MadAnalysis5 script to produce plots, cutflows, and reports.

    Args:
        events_path: Process directory from madgraph_launch (contains Events/).
        script: MA5 commands with {EVENTS_DIR} placeholder for event file paths.
            The placeholder is replaced with the actual path to the events directory.
            Do NOT include a `submit` command — it is appended automatically.
            Any user-written `submit` lines are stripped before execution.
            Example: "import {EVENTS_DIR}/Events/run_01/unweighted_events.lhe.gz as signal"
        target_path: Where to download the analysis output directory.
        level: Analysis level - "parton" (LHE), "hadron" (HepMC), "reco" (LHCO/ROOT).
            Default: "parton"

    Returns:
        dict with keys:
            - success (bool): Whether analysis succeeded
            - output_dir (str): Path to analysis output directory (if success)
            - message (str): Human-readable status message

    Example:
        >>> result = madanalysis_process(
        ...     events_path="tmp/pp_wprime",
        ...     script="import {EVENTS_DIR}/Events/run_01/unweighted_events.lhe.gz as wprime\\n"
        ...            "set wprime.type = signal\\n"
        ...            "plot PT(mu+) 50 0 500",
        ...     target_path="tmp/ma5_output",
        ...     level="parton",
        ... )
        >>> if result["success"]:
        ...     print(f"Analysis output at: {result['output_dir']}")
    """

    try:
        args = {
            "events": events_path,
            "script": script,
            "level": level,
            "output": target_path,
        }

        result = magnus.run_blueprint("madanalysis-process", args=args)
        assert result is not None
        return json.loads(result)
    except:
        return {
            "success": False,
            "error": traceback.format_exc(),
        }
